% st_signflip_test - Sign-flip permutation test on paired differences
%
% Tests whether paired differences are centred above zero, without any
% distributional assumption and without the Statistics Toolbox.
%
% Reviewer 1 asked specifically for permutation tests. This is that test.
%
% NULL HYPOTHESIS
%   Under H0 the two paired conditions are exchangeable, so each observed
%   difference was equally likely to have come out with the opposite sign.
%   The null distribution is therefore generated by randomly flipping the
%   sign of each difference and recomputing the mean.
%
% USAGE:
%   p = st_signflip_test(d)
%   p = st_signflip_test(d, n_perm)
%   p = st_signflip_test(d, n_perm, tail)
%   [p, null_dist, obs] = st_signflip_test(...)
%
% INPUT:
%   d       - [n x 1] paired differences (condition A minus condition B).
%             NaNs are removed.
%   n_perm  - Monte Carlo permutations when exact enumeration is not used
%             (default: 10000)
%   tail    - 'right' (default) : H1 median(d) > 0
%             'left'            : H1 median(d) < 0
%             'both'            : H1 median(d) ~= 0
%
% OUTPUT:
%   p         - permutation p-value
%   null_dist - the null distribution of the mean difference
%   obs       - the observed mean difference
%
% EXACT VS MONTE CARLO
%   With n <= 20 all 2^n sign assignments are enumerated and the p-value is
%   exact. Above that a Monte Carlo sample of n_perm sign vectors is used,
%   with the Phipson & Smyth (2010) +1 correction so the p-value can never
%   be exactly zero — reporting p = 0 from a finite permutation sample is
%   not defensible.
%
% NOTES:
%   - Requires at least 3 non-NaN differences; returns NaN otherwise.
%   - The test statistic is the MEAN difference. The mean is used rather
%     than the median because it makes the exact enumeration a single
%     matrix product; for symmetric nulls the two give very similar
%     p-values. Report the median as the descriptive statistic alongside.
%
% EXAMPLE:
%   d = geometry_effect - solver_effect;   % one value per replicate
%   p = st_signflip_test(d, 10000, 'right');
%
% SEE ALSO:
%   st_bh_fdr, st_boot_ci_median, st_rank_biserial, st_group_stats
%
% -------------------------------------------------------------------------
% Copyright (c) 2026 University College London
% Department of Imaging Neuroscience
%
% Author: Maike Schmidt
% Email:  maike.schmidt.23@ucl.ac.uk
%
% This file is part of the MSG Forward Modelling Toolbox (msg_fwd).

function [p, null_dist, obs] = st_signflip_test(d, n_perm, tail)

if nargin < 2 || isempty(n_perm), n_perm = 10000;  end
if nargin < 3 || isempty(tail),   tail   = 'right'; end

d = d(:);
d = d(~isnan(d));
n = numel(d);

p         = NaN;
null_dist = [];
obs       = NaN;

if n < 3
    return;
end

obs = mean(d);

if n <= 20
    % Exact enumeration of all 2^n sign assignments
    n_total   = 2^n;
    bits      = double(bitget(repmat((0:n_total-1)', 1, n), repmat(1:n, n_total, 1)));
    signs     = 1 - 2*bits;              % {0,1} -> {+1,-1}
    null_dist = (signs * d) / n;
    exact     = true;
else
    signs     = 1 - 2*(rand(n_perm, n) < 0.5);
    null_dist = (signs * d) / n;
    exact     = false;
end

tol = eps(max(1, abs(obs)));

switch lower(tail)
    case 'right'
        cnt = sum(null_dist >= obs - tol);
    case 'left'
        cnt = sum(null_dist <= obs + tol);
    case 'both'
        cnt = sum(abs(null_dist) >= abs(obs) - tol);
    otherwise
        error('st_signflip_test:badTail', ...
            'Unknown tail "%s". Valid: right | left | both.', tail);
end

if exact
    p = cnt / numel(null_dist);
else
    % Phipson & Smyth (2010): never report p = 0 from a finite sample
    p = (cnt + 1) / (numel(null_dist) + 1);
end

p = min(p, 1);

end
